name: CI Workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    uses: actions/checkout@v2

    - name: Setup Node.js
    uses: actions/setup-node@v2
    with:
        node-version: '14'

    - name: Install dependencies
    run: |
        if ! npm ls vite > /dev/null 2>&1; then
        echo "Vite is not installed. Installing..."
        npm install --save-dev vite
        else
        echo "Vite is already installed."
        fi

    - name: Start development server
    run: npx vite